version: '3.8'

services:
  web:
    build: .
    container_name: genesis-etl-service
    command: gunicorn -b 0.0.0.0:8080 wsgi:app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=dev
      - MONGO_URI=${MONGO_URI}
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: genesis-mongo
    restart: always
    ports:
      - "0.0.0.0:27017:27017"  # Allow external connections
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ["mongod", "--bind_ip_all"]  # Allow connections from any IP

volumes:
  mongo_data: